'use strict'

const {
    PORT,
    IMG_PATH,
    SELF_SERVICE,
    BODY_LIMIT,
    MONGODB_URL,
    MONGODB_NAME,
    ALGO_ACCOUNT_INFO_URL,
    ALGO_API_KEY,
    ALGO_USDC_ASSET_ID,
    ALGO_BASE_SERVER,
    ALGO_WALLET_MNEMONIC,
    ALGO_WALLET_ADDRESS,
    ALGO_AMOUNT,
    LNPAY_WALLET_URL,
    LNPAY_API_KEY,
    LNPAY_WALLET_ADDRESS,
    LNPAY_DECODE_API,
    UPHOLD_API_URL,
    UPHOLD_USDC_PAIR

} = process.env

const SERVER_CONFIG = {
    PORT,
    IMG_PATH,
    SELF_SERVICE,
    BODY_LIMIT,
    MONGODB_URL,
    MONGODB_NAME,
    ALGO_ACCOUNT_INFO_URL,
    ALGO_API_KEY,
    ALGO_USDC_ASSET_ID: Number(ALGO_USDC_ASSET_ID),
    ALGO_WALLET_MNEMONIC,
    ALGO_BASE_SERVER,
    ALGO_AMOUNT,
    LNPAY_WALLET_URL,
    LNPAY_API_KEY,
    LNPAY_WALLET_ADDRESS,
    LNPAY_DECODE_API,
    UPHOLD_API_URL,
    UPHOLD_USDC_PAIR,
    ALGO_WALLET_ADDRESS

}

export default SERVER_CONFIG